"""set default, allow languages nullable

Revision ID: 9dd599c1495d
Revises: 579c613eff61
Create Date: 2018-08-04 12:38:08.601284

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9dd599c1495d'
down_revision = '579c613eff61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'languages_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'languages_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
