"""include vote direction

Revision ID: e6ac83ef4570
Revises: fc34137ad3ba
Create Date: 2020-11-05 20:04:51.029258

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e6ac83ef4570'
down_revision = 'fc34137ad3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote_information', 'current_direction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote_information', 'current_direction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
