"""Rename paid column to free

Revision ID: fc34137ad3ba
Revises: 205742d3b3f5
Create Date: 2020-09-30 22:35:20.007768

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fc34137ad3ba'
down_revision = '205742d3b3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'paid', new_column_name='free', existing_type=sa.Boolean, nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'free', new_column_name='paid', existing_type=sa.Boolean, nullable=True)
    # ### end Alembic commands ###
